import type { GetStaticPathsOptions, GetStaticPathsResult } from 'astro'
import { getStaticPaths } from './src/pages/open-graph/[...path].ts'

const routes = (await getStaticPaths({} as GetStaticPathsOptions)) as GetStaticPathsResult

/**  All the OpenGraph image paths as generated by our `getStaticPaths`. */
const paths = new Set(routes.map(({ params }) => params.path))

/**
 * Get the path to the OpenGraph image for a page
 * @param path Pathname of the page URL.
 * @param isFallback Whether or not this page is displaying fallback content.
 * @returns Path to the OpenGraph image if found. Otherwise, `undefined`.
 */
export function getOgImageUrl(path: string, isFallback: boolean): string | undefined {
	let imagePath = path.replace(/^\//, '').replace(/\/$/, '') + '.png'
	if (isFallback) {
		imagePath = imagePath.slice(imagePath.indexOf('/'))
	}
	if (paths.has(imagePath)) return '/open-graph/' + imagePath
}
